#!/usr/bin/env python3
"""Build Cosmic's static public website. Portal data is never compiled into HTML."""
from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parents[1]
SITE=ROOT/'site'
E=escape
NAV=[('index.html','Home'),('about.html','About'),('community.html','Community'),('join.html','Join'),('rules.html','Rules'),('core-hub.html','Core Hub'),('departments.html','Departments'),('businesses.html','Businesses'),('organizations.html','Organizations'),('media.html','Media'),('news.html','News'),('status.html','Status')]
ICONS={
 'arrow':'<path d="M4 12h16m-6-6 6 6-6 6"/>',
 'user':'<circle cx="12" cy="7" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/>',
 'people':'<circle cx="8" cy="7" r="3"/><path d="M2 21v-3a6 6 0 0 1 12 0v3M17 4a3 3 0 0 1 0 6m1 4c3 0 4 2 4 5v2"/>',
 'shield':'<path d="m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6Z"/><path d="m8 12 3 3 5-6"/>',
 'building':'<path d="M4 21V8h7V3h9v18M2 21h20M7 11v2m0 3v2m7-12h3m-3 4h3m-3 4h3m-3 4h3"/>',
 'book':'<path d="M12 5C9 3 5 3 2 4v15c3-1 7-1 10 1 3-2 7-2 10-1V4c-3-1-7-1-10 1Zm0 0v15"/>',
 'grid':'<rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/>',
 'briefcase':'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V3h8v4M3 13c5 3 13 3 18 0"/>',
 'pulse':'<path d="M2 12h5l3-8 4 16 3-8h5"/>',
 'search':'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/>',
 'menu':'<path d="M3 6h18M3 12h18M3 18h18"/>',
 'lock':'<rect x="4" y="10" width="16" height="12" rx="2"/><path d="M7 10V7a5 5 0 0 1 10 0v3m-5 5v3"/>',
 'camera':'<rect x="2" y="5" width="20" height="16" rx="2"/><circle cx="12" cy="13" r="4"/><path d="M7 5V2h10v3"/>',
 'discord':'<path d="m8 5-3 1c-2 3-3 6-3 10l5 3 2-2m7-12 3 1c2 3 3 6 3 10l-5 3-2-2M7 7c3-1 7-1 10 0M7 16c3 1 7 1 10 0"/><circle cx="8" cy="12" r="1"/><circle cx="16" cy="12" r="1"/>',
 'file':'<path d="M5 2h9l5 5v15H5Zm9 0v6h5M8 12h8m-8 4h8"/>',
 'check':'<path d="m5 12 4 4L19 6"/>',
 'help':'<circle cx="12" cy="12" r="9"/><path d="M9 8a3 3 0 0 1 6 0c0 3-3 2-3 5m0 3v1"/>',
}
def icon(k):return f'<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">{ICONS.get(k,ICONS["arrow"])}</svg>'
def btn(t,u='',primary=False,attr=''):
 cls='button'+(' primary' if primary else '')
 return f'<a class="{cls}" href="{E(u)}" {attr}>{t}<span class="arrow" aria-hidden="true">↗</span></a>' if u else f'<button class="{cls}" type="button" {attr}>{t}{icon("arrow")}</button>'
def reference_slice(x,y,w,h,cls='',label='',priority=False):
    """Display a section of the supplied reference sheet without modifying its bytes."""
    alt=f' role="img" aria-label="{E(label)}"' if label else ' aria-hidden="true"'
    image_style=f'width:{1536/w*100:.6f}%;left:{-x/w*100:.6f}%;top:{-y/h*100:.6f}%;'
    return f'<span class="sheet-slice {cls}" style="aspect-ratio:{w}/{h}"{alt}><img data-reference-image src="assets/cosmic-brand-reference.jpg" alt="" width="1536" height="768" style="{image_style}"'+(' fetchpriority="high"' if priority else ' loading="lazy"')+'></span>'
def brand():
    concept=reference_slice(29,355,277,139,'reference-brand',priority=True)
    return '<a class="brand" href="index.html" aria-label="Cosmic home">'+concept+'<span class="brand-symbol" data-brand-symbol aria-hidden="true">C</span><img class="brand-logo" data-brand-logo alt="" hidden><span class="wordmark" data-wordmark>COSMIC<small>SAN ANDREAS ROLEPLAY</small></span></a>'
def navlinks(items,active):return ''.join(f'<a href="{u}"'+(' aria-current="page"' if u==active else '')+f'>{t}</a>' for u,t in items)
def header(active):return f'''<a class="skip-link" href="#main">Skip to content</a><header class="site-header"><div class="wrap nav-top">{brand()}<nav class="primary-nav" aria-label="Main navigation">{navlinks(NAV[:6],active)}</nav><div class="nav-actions"><button class="search-button" data-open-search aria-label="Search Cosmic">{icon('search')}</button><a href="login.html" data-account-link>Log in</a><a class="button primary small" href="portal.html#apply">Apply now {icon('arrow')}</a><button class="menu-button" aria-expanded="false" aria-controls="mobile-nav" aria-label="Open menu" id="menu-toggle">{icon('menu')}</button></div></div><div class="subbar"><div class="wrap subbar-inner"><span class="subbar-label">EXPLORE COSMIC</span><nav class="secondary-nav" aria-label="Explore navigation">{navlinks(NAV[6:],active)}</nav><a class="subbar-status" href="status.html" data-launch-label>Whitelist transition planned</a></div></div><nav class="mobile-nav" id="mobile-nav" aria-label="Mobile navigation" hidden>{navlinks(NAV,active)}<a href="login.html">Member login</a></nav></header>'''
def footer():return f'''<footer class="site-footer"><div class="wrap"><div class="footer-grid"><div>{brand()}<p>A city shaped by its people.<br>A community worth coming back to.</p></div><div class="footer-group"><h3>Discover</h3>{navlinks(NAV[:3],'')}{navlinks(NAV[6:9],'')}</div><div class="footer-group"><h3>Your next chapter</h3>{navlinks(NAV[3:6],'')}<a href="login.html">Member portal</a><a href="portal.html#apply">Whitelist application</a><a href="portal.html#requests">Support &amp; requests</a></div><div class="footer-group"><h3>Stay connected</h3>{navlinks(NAV[9:],'')}<button data-link="discord">Discord ↗</button><a href="privacy.html">Privacy &amp; data</a><a href="portal-preview.html" data-design-preview>Portal design preview</a></div></div><div class="footer-bottom"><p>© <span data-year>2026</span> Cosmic. Independent roleplay community. Not affiliated with or endorsed by Rockstar Games or Take-Two Interactive.</p><span>BUILT AROUND THE COMMUNITY.</span></div></div></footer>'''
def dialogs():return '''<dialog id="message-dialog" aria-labelledby="message-title"><div class="dialog-top"><h2 id="message-title">Connection pending</h2><button class="dialog-close" data-close-dialog aria-label="Close dialog">×</button></div><p id="message-copy"></p></dialog><dialog id="search-dialog" aria-labelledby="search-title"><div class="dialog-top"><h2 id="search-title">Explore Cosmic</h2><button class="dialog-close" data-close-dialog aria-label="Close search">×</button></div><label class="sr-only" for="site-search">Search pages and guides</label><input id="site-search" type="search" placeholder="Search rules, departments, guides..." autocomplete="off"><div class="search-results" id="search-results" aria-live="polite"></div></dialog>'''
SEARCH=[]
def page(file,title,description,body,portal=False,preview=False,extra_css=''):
 SEARCH.append({'title':title,'url':file,'description':description})
 shell=body if portal else header('departments.html' if file.startswith('department-') else file)+f'<main id="main" tabindex="-1">{body}</main>'+footer()
 scripts='<script defer src="assets/config.js"></script><script defer src="assets/data.js"></script><script defer src="assets/content.js"></script><script defer src="assets/app.js"></script>'
 if portal or file in ('login.html','auth-callback.html'):scripts+='<script defer src="assets/auth.js"></script>'
 if portal:scripts+='<script defer src="assets/department-hub.js"></script><script defer src="assets/portal.js"></script>'
 if preview:scripts+='<script defer src="assets/preview.js"></script>'
 noindex='<meta name="robots" content="noindex,nofollow">' if portal or file in ('login.html','auth-callback.html','portal-preview.html') else ''
 csp="default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https:; font-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'; upgrade-insecure-requests"
 html=f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#090e14"><meta name="description" content="{E(description)}"><meta name="referrer" content="no-referrer"><meta http-equiv="Content-Security-Policy" content="{csp}">{noindex}<meta property="og:title" content="{E(title)} | Cosmic"><meta property="og:description" content="{E(description)}"><meta property="og:type" content="website"><title>{E(title)} | Cosmic</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/styles.css"><link rel="stylesheet" href="assets/brand.css">{scripts}</head><body data-page="{file[:-5]}"{' data-preview="true"' if preview else ''}><noscript><div class="no-script">Public content is available below. Enable JavaScript for search, member login and portal features.</div></noscript>{shell}{dialogs()}</body></html>'''
 if portal:html=html.replace('</head>','<link rel="stylesheet" href="assets/department-hub.css"></head>')
 if extra_css:html=html.replace('</head>',f'<link rel="stylesheet" href="{E(extra_css)}"></head>')
 (SITE/file).write_text(html,encoding='utf-8')
def hero(title,desc,kicker='Explore Cosmic',actions=''):
 return f'<section class="page-hero"><div class="wrap"><div class="breadcrumbs"><a href="index.html">Home</a><span>/</span><span>{title.title()}</span></div><span class="eyebrow">{kicker}</span><h1>{title}</h1><p class="lead">{desc}</p>{actions}</div></section>'
def notice(t):return f'<div class="notice">{t}</div>'
def section(content,cls=''):return f'<section class="section {cls}"><div class="wrap">{content}</div></section>'
def card(title,desc,ico='grid',link=None,label='Explore',cls=''):
 content=f'<div class="card-icon">{icon(ico)}</div><h3>{title}</h3><p>{desc}</p>'
 if link:content+=f'<span class="text-link">{label} {icon("arrow")}</span>'
 return f'<a class="card path-card {cls}" href="{link}">{content}</a>' if link else f'<div class="card {cls}">{content}</div>'
def cta():return '<div class="wrap"><section class="cta"><div><h2>YOUR NEXT CHAPTER STARTS HERE.</h2><p>Meet the community. Find your story. Make it Cosmic.</p></div><div class="button-row">'+btn('How to join','join.html',True)+btn('Member login','login.html')+'</div></section></div>'

home=f'''<section class="hero hero-rebrand"><div class="cinema-stage">{reference_slice(0,0,1536,346,'cinema-reference','Provisional Cosmic Roleplay branding over a sunset San Andreas city scene',True)}<img class="cinema-custom" data-hero-image alt="Cosmic community cover" hidden><div class="cinema-caption"><span>SAN ANDREAS / A WORLD OF POSSIBILITIES</span><a href="about.html">DISCOVER COSMIC {icon('arrow')}</a></div></div><div class="wrap hero-inner"><span class="eyebrow">THE NEXT CHAPTER OF COSMIC ROLEPLAY</span><h1>A CITY TO CALL <span>HOME.</span></h1><p>Make a name. Find your people. Write a story worth coming back to.</p><div class="button-row">{btn('Begin your story','join.html',True)}{btn('Member login','login.html')}</div><div class="hero-footer"><span>YOUR CHARACTER. YOUR CHOICES. OUR COMMUNITY.</span><a href="#discover">EXPLORE THE CITY ↓</a></div></div></section><div class="rail"><div class="wrap">{''.join(f'<div class="rail-item">{icon(i)}<span>{t}</span></div>' for i,t in [('people','Community first'),('shield','A whitelisted future'),('building','Player-driven stories'),('grid','One connected portal')])}</div></div>'''

home+=section('''<div class="intro-grid" id="discover"><div><span class="eyebrow">More than a server</span><h2>THE CITY IS THE SETTING.<br>THE PEOPLE MAKE IT COSMIC.</h2></div><div><p>Build something that lasts beyond a single scene. A reputation, a business, a circle of friends, or a character you cannot wait to return to.</p><p>Cosmic brings those stories together, with a new community portal and a move toward whitelisted roleplay at the heart of its next chapter.</p><a class="text-link" href="about.html">Get to know Cosmic <span class="arrow">↗</span></a></div></div>''')
home+=section('<div class="section-head"><div><span class="eyebrow">Find your direction</span><h2>ONE CITY. YOUR POSSIBILITIES.</h2></div><p>There is no single way to belong here. Discover the people and places that make your character’s life their own.</p></div><div class="grid-3">'+card('Answer the call.','Explore public service, law enforcement, and fire and medical roleplay.','shield','departments.html','Explore departments')+card('Build your future.','Put a name above the door. Turn a business idea into stories people return to.','briefcase','businesses.html','Discover businesses')+card('Find your people.','Clubs, crews, and organizations with a shared identity and a story to tell.','people','organizations.html','Explore organizations')+'</div>','compact')
home+=section(f'''<div class="portal-feature"><div><span class="eyebrow">The Cosmic portal</span><h2>LESS SEARCHING.<br>MORE BELONGING.</h2><p>Your application, your updates, and your member resources. One place to find your next step, whether you are new to Cosmic or already part of the community.</p>{btn('Explore the joining process','join.html')}</div><div class="portal-mini" aria-label="Illustrative member portal preview"><header><span class="avatar">C</span><div class="mini-copy"><b>Your Cosmic account</b><small>PORTAL DESIGN PREVIEW</small></div></header><div class="mini-list"><div>Whitelist application <span>Track progress</span></div><div>Core Hub <span>Member resources</span></div><div>Departments &amp; opportunities <span>Find your place</span></div><div>Support &amp; requests <span>Stay connected</span></div></div></div></div>''','compact')
home+=section('<div class="section-head"><div><span class="eyebrow">The next chapter</span><h2>WHAT’S TAKING SHAPE.</h2></div><a class="text-link" href="news.html">Visit the newsroom '+icon('arrow')+'</a></div><div class="grid-3">'+''.join(f'<a class="card news-card" href="{u}"><div class="news-art"><span class="news-cityline" aria-hidden="true"></span><span class="display">{art}</span></div><span class="meta">PLANNED / EDITORIAL PREVIEW</span><h3>{t}</h3><p>{d}</p><span class="text-link">Read more {icon("arrow")}</span></a>' for art,t,d,u in [('COSMIC','Same name. A new chapter.','A refreshed identity and a home for everything Cosmic.','news-rebrand.html'),('ACCESS','A whitelisted future.','A clear path from application to community membership.','news-whitelist.html'),('HUB','Your community, connected.','Public information and member tools, brought together.','news-portal.html')])+'</div>')+cta()
page('index.html','Home','Cosmic is a FiveM roleplay community preparing its next chapter, with whitelisted access and a connected member portal.',home)
page('about.html','About','Get to know the community and the next chapter of Cosmic.',hero('THIS IS COSMIC.','The city gives us a setting. The people give it a reason to matter.','About the community')+section('<div class="intro-grid"><div><span class="eyebrow">A place to belong</span><h2>CREATE A CHARACTER.<br>FIND A COMMUNITY.</h2></div><div><p>Cosmic is built around the stories people create together. The ordinary moments matter as much as the dramatic ones: opening a shop, working a shift, meeting your neighbors, and finding your place.</p><p>Our next chapter brings a refreshed identity, a move toward whitelisted membership, and a connected website and portal. The name stays Cosmic. The opportunities keep growing.</p></div></div>')+section('<div class="grid-3">'+card('People before numbers.','We want a community people enjoy returning to, not a scoreboard of account totals.','people')+card('Stories with room to grow.','Build relationships, share the spotlight, and leave room for other characters to surprise you.','book')+card('Clear places to turn.','Rules, resources, application progress, and support should be easy to find.','grid')+'</div>','compact')+cta())
page('community.html','Community','Find the community spaces, creator information, and ways to get involved in Cosmic.',hero('YOUR PEOPLE ARE HERE.','Meet the community behind the characters. Find a place to talk, create, and get involved.','Community')+section('<div class="grid-3">'+card('The conversation starts here.','Discord is the intended home for community conversation, announcements, and getting to know the people behind the characters.','discord')+card('Creators & storytellers.','Show the city through your own lens. Creator opportunities and requirements will be published after the program is confirmed.','camera')+card('Have an idea?','Member requests give your proposals a home and a visible progress trail.','help','portal.html#requests','Open member requests')+'</div><div class="button-row" style="margin-top:28px">'+btn('Join the Discord',attr='data-link="discord"')+btn('Explore organizations','organizations.html')+'</div>')+section('<div class="section-head"><div><span class="eyebrow">Community calendar</span><h2>MAKE TIME FOR THE CITY.</h2></div></div><div class="empty-state">'+icon('people')+'<h3>Official events will appear here.</h3><p>No event dates have been published in this build. Confirmed community events can be added without changing the page layout.</p></div>','compact')+cta())
steps=[('01','Meet Cosmic','Read about the community and the direction of its next chapter.'),('02','Read the rules','Use the approved rulebook once published. The current text is a draft.'),('03','Sign in & apply','Connect your Discord account and complete the whitelist application when intake opens.'),('04','Follow your progress','See staff feedback and your decision in the portal. Server activation is confirmed separately.')]
page('join.html','Join','The path to joining Cosmic and its planned whitelisted community.',hero('YOUR STORY STARTS HERE.','A clear path into the community, from your first visit to your first chapter in the city.','Join Cosmic','<div class="button-row">'+btn('Go to applications','portal.html#apply',True)+btn('Read the rules','rules.html')+'</div>')+section(notice('<b>Whitelist transition planned.</b> Applications remain closed in the backend until the team approves the rulebook and opens intake. Creating an account is not whitelist approval.')+'<div class="steps" style="margin-top:32px">'+''.join(f'<div class="step"><span class="step-num">{n}</span><h3>{t}</h3><p>{d}</p></div>' for n,t,d in steps)+'</div>')+section('<div class="grid-2">'+card('What you can prepare','A character concept, a reason you want to join Cosmic, and examples of how you would handle shared roleplay. Final eligibility requirements will be set by the team.','file')+card('After you are approved','The portal unlocks member resources and additional requests. Portal approval does not automatically add Discord roles or authorize a FiveM connection.','lock')+'</div>','compact')+section(''.join(f'<details class="accordion"><summary>{q}</summary><p>{a}</p></details>' for q,a in [('Is the whitelist open yet?','This build does not announce an opening date. Intake is closed by default and must be opened by the community owner.'),('Do I need a separate website password?','This portal uses Discord sign-in. Cosmic does not ask you to enter your Discord password on this website.'),('Does signing in make me a member?','No. A new account starts as an applicant. Whitelist approval and any server activation happen separately.'),('Can I save my application?','Once the backend is configured, you can save a private draft and return to it. Submission is available only when the team opens intake.')]),'compact'))
RULES=[
 ('community','Respect the people behind the characters.','Keep out-of-character interactions respectful. Do not harass, threaten, discriminate against, or expose the private information of other players. This is proposed wording and requires staff approval.'),
 ('roleplay','Keep in-character knowledge in character.','Do not give your character information learned through streams, private messages, or other out-of-character sources. Exact metagaming rules and exceptions must be approved by the team.'),
 ('roleplay','Give other players room to respond.','Do not force another character’s actions or outcomes. Describe your attempt and allow a reasonable response. Specific mechanics and powergaming examples remain subject to the approved rulebook.'),
 ('roleplay','Make conflict part of a story.','Conflict should create roleplay, not end another player’s experience for its own sake. Combat initiation, robbery, escalation, and injury rules must be added by the team before launch.'),
 ('fairplay','Do not exploit the game or the community.','Do not use cheats, unintended exploits, or unauthorized tools to gain an advantage. Report suspected exploits privately instead of sharing reproduction instructions publicly.'),
 ('fairplay','Handle interrupted scenes responsibly.','When a crash or connection problem interrupts a scene, contact the involved players or staff through the approved channel. Reconnection windows and scene-exit procedures must be finalized.'),
 ('community','Keep reports out of the middle of a scene.','Preserve relevant evidence and use the approved report process when practical. Immediate safety concerns should be raised with staff without waiting for a scene to end.'),
 ('community','Use the current approved rulebook.','This website text is a proposed starter framework, not an adopted Cosmic policy. Eligibility, sanctions, appeals, restricted content, and detailed department rules have not been established by this build.')]
rulebody=hero('THE RULEBOOK.','A shared understanding is where good roleplay begins. Find the standards that help everyone share the city.','Community rules')+section('<div class="notice warning" data-rules-notice><b>DRAFT RULEBOOK, NOT ADOPTED POLICY.</b> The entries below are proposed starting points. Staff must review, replace, and approve them before applications open.</div><div class="filters" style="margin-top:25px"><button class="filter" data-rule-filter="all" aria-pressed="true">All rules</button><button class="filter" data-rule-filter="community" aria-pressed="false">Community</button><button class="filter" data-rule-filter="roleplay" aria-pressed="false">Roleplay</button><button class="filter" data-rule-filter="fairplay" aria-pressed="false">Fair play</button></div>'+''.join(f'<details class="accordion" data-rule-category="{c}"><summary>{i:02d}. {t}</summary><p>{d}</p></details>' for i,(c,t,d) in enumerate(RULES,1)))
page('rules.html','Rules','Read Cosmic’s rulebook area. Current wording is a draft for team approval.',rulebody)
GUIDES=[
 ('getting-started','Getting started','New players','Find your first steps and learn how account access differs from whitelist approval.','Start with About and Community to understand Cosmic. Read the approved rules before applying.\n\nAfter Discord sign-in, your portal account is an applicant account. You can prepare a draft when the backend is configured. Staff open submissions only after approving the rulebook.\n\nUse My Applications to read the decision and any requested changes. An approved application unlocks website member resources. A separate server-side whitelist must confirm that you can join FiveM.'),
 ('character','Building a character','Roleplay','Create someone with goals, relationships, and room to develop.','Give your character a reason to be in the city and something to work toward. A useful concept has strengths, limitations, and open questions.\n\nThink about what your character does on an ordinary day. Who would they look for? What kind of work interests them? What could change their plans?\n\nLeave room for other players to influence your story. Character names, prohibited backgrounds, multiple-character limits, and related policies must follow the approved rulebook.'),
 ('knowledge','Character knowledge','Roleplay','A starting point for understanding in-character and out-of-character information.','The player may know more than the character. Information from streams, Discord conversations, or other characters is not automatically knowledge your character can use.\n\nA useful question is: how did my character learn this during roleplay? When the answer is unclear, ask staff before acting on the information.\n\nThis guide is explanatory draft content. The approved Cosmic rulebook takes precedence.'),
 ('business','Starting a business','City life','Prepare a concept that creates reasons for other characters to interact.','Describe the service your business offers, where you hope to operate, and what makes it useful to the city. Include a staffing idea and examples of the roleplay it could generate.\n\nThe website contains no confirmed inventory of available properties or approved purchase prices. Staff must approve any location, concept, ownership change, and supported mechanics.\n\nApproved members can submit a business proposal through Requests once that intake is enabled. Website approval does not create an in-game business automatically.'),
 ('organizations','Finding your circle','City life','Turn a shared idea into an organization with its own identity.','An organization needs a shared purpose, a recognizable identity, and a reason to interact with people outside its membership. A social club, car crew, or other group can each create a different kind of roleplay.\n\nPrepare your concept, expected activities, and contact person before requesting recognition. Criminal organizations remain subject to the approved server rules and any organization-specific limits.\n\nRecognition, roster management, ranks, and in-game permissions are not automatically granted by website approval.'),
 ('support','Getting help','Community','Find the right route for questions, feedback, and support.','Use a support request for account or community issues. Describe what happened, the outcome you need help with, and the relevant time or application reference.\n\nDo not include passwords, authentication tokens, payment details, or unnecessary personal information. This build accepts text only and does not upload evidence files.\n\nFor urgent matters, use the official Discord support route once it is configured. This portal is not an emergency service.'),
 ('departments','Department pathways','City life','Explore public-service roleplay before submitting an interest application.','Public department pages explain possible roleplay paths. Their existence does not mean a department is currently recruiting.\n\nRead the department’s official requirements and current recruitment information before applying. A member request can record your area of interest and relevant roleplay experience.\n\nDepartment approval, training, ranks, and duty access require separate staff action. Sensitive operating procedures belong in the protected Core Hub, not in the public website source.'),
 ('account','Your account & privacy','Community','Understand what the portal stores and how to ask for assistance.','Discord sign-in authenticates your website account. New users receive an applicant role, not staff permissions or approved membership.\n\nThe configured backend stores your profile, application answers, application feedback, and workflow history. Only your own records and records your role is authorized to review should be accessible.\n\nUse the profile page to export your profile and application data. Account deletion is a staff-assisted request in this build. Retention, owner contact details, and a final privacy notice must be established before launch.')]
filters='<div class="filters">'+''.join(f'<button class="filter" data-guide-filter="{c}" aria-pressed="{str(i==0).lower()}">{c}</button>' for i,c in enumerate(['All','New players','Roleplay','City life','Community']))+'</div>'
guidecards=''.join(f'<a class="card guide-card" data-guide-card data-category="{c}" data-search="{E((t+" "+d+" "+text).lower())}" href="guide-{slug}.html"><span class="category">{c}</span><h3>{t}</h3><p>{d}</p><span class="text-link">Open guide {icon("arrow")}</span></a>' for slug,t,c,d,text in GUIDES)
page('core-hub.html','Core Hub','Cosmic’s central place for public guides and protected member resources.',hero('THE CORE HUB.','Your starting point for guides, community information, and resources that help you find your way.','Knowledge & resources')+section('<div class="section-head"><div><span class="eyebrow">Find what you need</span><h2>A LITTLE LESS GUESSWORK.</h2></div><a class="text-link" href="portal.html#resources">Open member resources '+icon('lock')+'</a></div><label class="sr-only" for="guide-search">Search guides</label><div class="search-field" style="margin:0 0 25px">'+icon('search')+'<input id="guide-search" placeholder="Search guides and resources..." type="search"></div>'+filters+'<div class="grid-3" id="guide-grid">'+guidecards+'</div><p id="guide-empty" hidden>No guides match your search.</p>')+section(notice('<b>Public guides and private resources are separate.</b> Protected member or staff material is loaded from the backend after authorization. It is never bundled into these public guide pages.'),'compact'))
for slug,t,c,d,text in GUIDES:
 page('guide-'+slug+'.html',t,d,hero(t.upper(),d,c)+section('<div class="prose">'+notice('Guide draft for review. Approved server rules take precedence.')+''.join('<p style="margin-top:22px">'+E(p)+'</p>' for p in text.split('\n\n'))+'<div class="button-row" style="margin-top:30px">'+btn('Back to Core Hub','core-hub.html')+'</div></div>'))
from department_pages import build_lspd
build_lspd(page, icon, btn)

DEPARTMENT_CONCEPTS=[
    ('LSPD','Los Santos Police Department','City policing and public-service stories.',(584,532,132,89),'shield'),
    ('BCSO',"Blaine County Sheriff’s Office",'County communities and the roads between them.',(733,532,135,89),'shield'),
    ('SASP','San Andreas State Police','A statewide law-enforcement identity.',(880,536,151,87),'shield'),
    ('FMA','Fire & Medical Authority','Emergency response and patient-care stories.',(582,634,139,79),'pulse'),
    ('DOJ','Department of Justice','The legal and judicial side of the city.',(724,626,148,92),'building'),
    ('ICO','Internal Community Operations','A proposed home for internal community functions.',(874,632,168,86),'people'),
]
def department_concepts():
    cards=''
    for code,title,desc,rect,ico in DEPARTMENT_CONCEPTS:
        art=reference_slice(*rect,'department-reference')
        url,label=('department-lspd.html','Explore LSPD') if code=='LSPD' else ('guide-departments.html','About department pathways')
        category='DEPARTMENT OVERVIEW' if code=='LSPD' else 'BRAND-REFERENCE CONCEPT'
        cards+=f'<article class="card department-card"><div class="department-identity">{art}<span class="department-fallback">{E(code)}</span></div><span class="category">{category}</span><h3>{E(title)}</h3><p>{E(desc)}</p><a class="text-link" href="{url}">{label} {icon("arrow")}</a></article>'
    return '<div class="grid-3 department-grid">'+cards+'</div>'
page('departments.html','Departments','Explore the department identities proposed in Cosmic’s brand reference.',hero('A CITY WORTH SERVING.','Different callings. A shared community. Discover the public-service side of Cosmic.','Departments')+section(notice('<b>Proposed identities, not an active roster.</b> These six concepts come from the brand reference. Names, responsibilities, access, and recruitment still require confirmation. No applications are announced as open.')+department_concepts())+section('<div class="grid-2">'+card('Public information','Confirmed introductions, recruitment details, and approved public documents will have a home here.','book','guide-departments.html','Explore department pathways')+card('Internal resources','Open your department’s private notices and employee roster after Discord role verification.','lock','portal.html#departments','Open My departments')+'</div>','compact'))

page('businesses.html','Businesses','Discover player businesses and proposal pathways in Cosmic.',hero('PUT YOUR NAME ON IT.','Create a reason for people to stop, stay, and come back. Business ownership starts with a story worth sharing.','Businesses','<div class="button-row">'+btn('Submit a proposal','portal.html#requests',True)+btn('Read the business guide','guide-business.html')+'</div>')+section('<div class="grid-2">'+card('Established businesses','Existing locations can be listed here once their ownership and availability are confirmed. No prices, vacancies, or purchase options are assumed.','building')+card('Original ideas','Pitch a new concept with its purpose, preferred location, staffing plan, and the roleplay it creates. Approval depends on the concept and server compatibility.','briefcase')+'</div>')+section('<div class="section-head"><div><span class="eyebrow">Business directory</span><h2>THE PEOPLE BEHIND THE COUNTER.</h2></div></div><div id="business-directory" class="grid-3"></div><div class="empty-state" id="business-empty">'+icon('briefcase')+'<h3>Confirmed businesses will be listed here.</h3><p>Only approved listings should appear in the directory. Businesses can be added through the public content file after owner review.</p></div>','compact'))
page('organizations.html','Organizations','Find Cosmic’s clubs, crews, and organization proposal area.',hero('FIND YOUR CIRCLE.','A shared identity. A common purpose. People who turn a character’s story into something bigger.','Organizations','<div class="button-row">'+btn('Propose an organization','portal.html#requests',True)+btn('Read the organization guide','guide-organizations.html')+'</div>')+section('<div class="grid-3">'+card('Clubs & communities','Gather around a shared interest, a social space, or a cause your characters care about.','people')+card('Crews & collectives','Build an identity through shared projects, events, and the roleplay you create with others.','grid')+card('Criminal organizations','Concepts and activities require staff approval and must follow the final criminal-roleplay and organization rules.','shield')+'</div>')+section('<div class="section-head"><div><span class="eyebrow">Organization directory</span><h2>A NAME THAT MEANS SOMETHING.</h2></div></div><div id="organization-directory" class="grid-3"></div><div class="empty-state" id="organization-empty">'+icon('people')+'<h3>Official organizations will appear here.</h3><p>No group is presented as approved, active, or recruiting until its listing has been confirmed.</p></div>','compact'))
page('media.html','Media','The home for approved Cosmic screenshots, trailers, and community creations.',hero('THE CITY, THROUGH YOUR EYES.','Moments worth keeping. Characters worth remembering. A place for the community’s view of Cosmic.','Media')+section('<div class="section-head"><div><span class="eyebrow">From the community</span><h2>MAKE A MOMENT OF IT.</h2></div><p>Real server screenshots and approved videos can replace these media slots when the new branding is ready.</p></div><div id="media-gallery" class="grid-2"></div><div id="media-placeholders" class="grid-2">'+''.join(f'<div class="media-slot">{icon("camera")}<strong>{t}</strong><small>Awaiting approved community media</small></div>' for t in ['The city after dark','The people who make it home'])+'</div>')+section('<div class="grid-2">'+card('Share your perspective','Members can send creator inquiries through the portal. This release records text requests and does not accept direct media uploads.','camera','portal.html#requests','Open requests')+card('Official channels','Official social channels are connected only after the community supplies the correct links.','discord')+'</div><div class="button-row" style="margin-top:25px">'+btn('YouTube',attr='data-link="youtube"')+btn('Twitch',attr='data-link="twitch"')+btn('Discord',attr='data-link="discord"')+'</div>','compact'))
NEWS=[('rebrand','Same name. A new chapter.','Cosmic is preparing a refreshed visual identity.','The name is staying Cosmic. The visual identity is changing.\n\nThis website is using a provisional charcoal, silver, and ice-blue direction inspired by the supplied city-themed brand reference. Its colors, logo, and key images are configurable so the final identity can be applied consistently.\n\nThis article is draft announcement copy. The team should approve its wording and add a publication date before using it as official news.'),('whitelist','A whitelisted future.','A clear route from your first visit to community membership.','Cosmic is planning a move to whitelisted access.\n\nThe new portal separates account creation, application review, and approved membership. Applicants can follow their progress and read feedback without confusing a login with permission to enter the server.\n\nNo launch date, eligibility threshold, or review turnaround is announced by this draft. The team will publish confirmed requirements and open submissions when ready.'),('portal','Your community, connected.','Public information and member tools in one home.','The website brings Home, About, Community, Join, Rules, Core Hub, Departments, Businesses, Organizations, Media, News, and Status together.\n\nThe member side is designed around applications, private resources, requests, and account settings, with a separate review workspace for authorized staff.\n\nThis is preview copy for an unlaunched system. Connected services and permissions must be configured and tested before real member information is collected.')]
page('news.html','News','News and announcements from Cosmic. Current articles are editorial previews.',hero('FROM THE TEAM.','Community news, development notes, and the next chapter of Cosmic.','News & announcements')+section(notice('<b>Editorial previews.</b> The articles below are draft announcement copy, not dated releases or a claim that the portal is live.')+'<div class="grid-3" style="margin-top:28px">'+''.join(f'<a class="card news-card" href="news-{s}.html"><div class="news-art"><span class="news-cityline" aria-hidden="true"></span><span class="display">{a}</span></div><span class="meta">DRAFT / NOT YET PUBLISHED</span><h3>{t}</h3><p>{d}</p><span class="text-link">Read preview {icon("arrow")}</span></a>' for (s,t,d,b),a in zip(NEWS,['COSMIC','ACCESS','HUB']))+'</div>'))
for s,t,d,b in NEWS:
 page('news-'+s+'.html',t,d,hero(t.upper(),d,'Editorial preview')+section('<article class="prose">'+notice('Draft announcement. Publication date and final wording await team approval.')+''.join('<p style="margin-top:24px">'+E(p)+'</p>' for p in b.split('\n\n'))+'<div class="button-row" style="margin-top:30px">'+btn('Back to news','news.html')+'</div></article>'))
page('status.html','Status','See verified service status when an official monitoring endpoint is connected.',hero('KEEP UP WITH THE CITY.','Connection information and service updates, without guesswork.','Service status')+section('<div class="status-stack"><div class="status-row"><div><h3>FiveM game server</h3><p id="status-detail">No official monitoring endpoint has been connected.</p></div><span class="pill" id="server-status">Status unavailable</span></div><div class="status-row"><div><h3>Whitelist applications</h3><p>Intake is controlled by the team in the authenticated portal.</p></div><a class="pill" href="portal.html#apply">Check portal</a></div><div class="status-row"><div><h3>Community Discord</h3><p>This page does not independently monitor Discord availability.</p></div><button class="button small" data-link="discord">Open Discord ↗</button></div></div><p class="muted-text" id="status-time" style="margin-top:16px">No live player count or uptime data is displayed until verified.</p><div class="button-row" style="margin-top:25px"><button class="button" id="refresh-status">Refresh status '+icon('pulse')+'</button></div>')+section('<div class="empty-state">'+icon('pulse')+'<h3>Incident reporting is not connected.</h3><p>This build has no incident-history service. Absence of an incident here does not mean every service is online.</p></div>','compact'))
page('login.html','Member login','Sign in to your Cosmic account using Discord.',f'<div class="wrap"><section class="auth-layout"><div class="auth-copy"><span class="eyebrow">The Cosmic portal</span><h1>YOUR COMMUNITY.<br>ONE CONNECTION.</h1><p>Save your application, follow your progress, and find the tools that come with being part of Cosmic.</p><p class="muted-text">Signing in creates an applicant account. Whitelist membership is reviewed separately.</p></div><div class="auth-card"><h2>Welcome to Cosmic.</h2><p>Use your Discord account to continue. New here? Your portal account is created on your first successful sign-in.</p>{btn('Continue with Discord',primary=True,attr='id="discord-login"')}<div id="auth-notice" class="notice">Checking account connection...</div><p id="auth-message" class="message" aria-live="polite"></p><p class="tiny">You will authenticate on Discord’s official site. Never enter your Discord password into a Cosmic form. Read our <a href="privacy.html"><u>privacy information</u></a> before continuing.</p><a href="portal-preview.html" class="text-link" data-design-preview style="margin-top:20px">View the read-only portal design ↗</a></div></section></div>')
page('auth-callback.html','Completing sign-in','Complete your Discord sign-in and return to Cosmic.',section('<div class="portal-load"><h2>CONNECTING YOUR ACCOUNT.</h2><p id="auth-notice">Completing your sign-in securely...</p><p id="auth-message" class="message" aria-live="polite"></p><div class="button-row">'+btn('Return to login','login.html')+'</div></div>'))
def portal_shell(preview=False):
 banner='<div class="preview-banner"><span><b>DESIGN PREVIEW.</b> Fictional sample account. Read-only. This is not a login or real member data.</span><label for="preview-role">Preview role <select id="preview-role"><option value="applicant">Applicant</option><option value="member" selected>Approved member</option><option value="staff">Staff reviewer</option></select></label></div>' if preview else ''
 return banner+f'<header class="portal-bar">{brand()}<div class="right"><span class="pill">MEMBER PORTAL</span><a href="index.html">Back to website ↗</a><button class="button small" id="sign-out"'+(' hidden' if preview else '')+f'>Sign out</button></div></header><div id="portal-root"><main id="main" class="portal-load"><h1>{"PORTAL DESIGN PREVIEW" if preview else "YOUR COSMIC ACCOUNT"}</h1><p>{"Loading the read-only preview..." if preview else "Checking your session and permissions..."}</p></main></div>'
page('portal.html','Member portal','Your Cosmic account, applications, requests, and private resources.',portal_shell(),portal=True)
page('portal-preview.html','Portal design preview','Read-only layout preview with fictional sample data. Not a real account or authentication.',portal_shell(True),portal=True,preview=True)
page('privacy.html','Privacy & data','What this build stores, what still needs owner configuration, and how to request assistance.',hero('YOUR ACCOUNT. YOUR INFORMATION.','A clear view of the data this portal is designed to use.','Privacy information')+section('<article class="prose">'+notice('<b>Pre-launch information, not a finalized privacy notice.</b> The community owner must add the operator’s identity, contact route, retention policy, applicable rights, and service details before collecting real applications.')+'<h2>PUBLIC WEBSITE</h2><p>The public site includes no advertising, analytics SDK, or tracking pixel. Your hosting provider may maintain access logs. External destinations have their own policies.</p><h2>AUTHENTICATION</h2><p>When configured, Discord handles identity sign-in through Supabase. The browser stores an authentication session needed to keep you signed in. Signing out removes the active local session. Cosmic does not collect your Discord password.</p><h2>PORTAL RECORDS</h2><p>The backend stores your user ID, display name, account access role, application answers, review feedback, and application workflow history. Supabase Auth may also hold profile or email information supplied by Discord. Do not enter passwords, payment details, or unnecessary real-world personal information into an application.</p><h2>DISCORD APPLICATION REVIEWS</h2><p>Submitted application answers, your display name, verified Discord user ID, application status, and staff feedback are shared with authorized reviewers in a private Cosmic Discord channel. Drafts are not sent to Discord. Staff can approve, deny, or request changes there; their feedback is visible to you in the portal. Discord stores a separate copy of the review message and attached answers. Withdrawing an application does not erase its history, and deleting database records does not automatically remove the Discord copy.</p><h2>ACCESS, EXPORT &amp; DELETION</h2><p>Your profile page can export your profile and application records. Staff can review application data only through authorized backend access. Deletion is a staff-assisted request in this release, not an automatic deletion button. The owner must publish an accessible contact route and document record retention before launch.</p><h2>NO HIDDEN PRIVATE FILES</h2><p>Public HTML and repository files are not private storage. Member and staff resource content belongs in the access-controlled database. External documents and files must have their own appropriate access controls.</p><div class="button-row" style="margin-top:25px">'+btn('Open account settings','portal.html#profile')+btn('Contact support',attr='data-link="support"')+'</div></article>'))
page('404.html','Page not found','The requested page could not be found.',hero('A WRONG TURN.','The page you are looking for is not here. Head back to the city’s front door.','404','<div class="button-row">'+btn('Back to Home','index.html',True)+btn('Open Core Hub','core-hub.html')+'</div>'))
# Search data contains public content only. Keep private resources out of this file.
search=[p for p in SEARCH if p['url'] not in ('portal.html','portal-preview.html','auth-callback.html','404.html')]
(SITE/'assets/data.js').write_text('window.COSMIC_PAGES = '+json.dumps(search,ensure_ascii=False)+';\n',encoding='utf-8')
if not (SITE/'assets/content.js').exists():
 (SITE/'assets/content.js').write_text('''// Public approved content only. These arrays intentionally start empty.
window.COSMIC_CONTENT = {
  businesses: [], // {name, description, category, url} with approved public destinations only.
  organizations: [], // {name, description, category, url}
  media: [] // {src: 'assets/your-screenshot.webp', alt, caption}. Publish only permitted images.
};
''')
(SITE/'assets/favicon.svg').write_text('<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="62" height="62" x="1" y="1" rx="13" fill="#0b111a" stroke="#8ac7f3" stroke-width="2"/><path d="M45 20H24l-6 6v19l6 6h21V40H30V30h15Z" fill="#d9eafa"/><path d="M18 52h28" stroke="#4b92ca" stroke-width="2"/></svg>')
(SITE/'.nojekyll').touch()
(SITE/'robots.txt').write_text('User-agent: *\nDisallow: /portal.html\nDisallow: /portal-preview.html\nDisallow: /auth-callback.html\nDisallow: /tools/\n')
print('Built',len(SEARCH),'pages.')
